name: flutter_application_2
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #GoRouter
  go_router: ^14.2.0

  #CupertinoIcons
  cupertino_icons: ^1.0.6

  #FontAwesome
  font_awesome_flutter: ^10.7.0

  #BloC
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  #GoogleFonts
  google_fonts: ^6.2.1

  #CurvedNavigator
  curved_navigation_bar: ^1.0.3

  #FireBase
  firebase_auth: ^5.1.2
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  flutterfire_cli: ^1.0.0

  #Isar
  isar: ^3.1.0+1
  isar_generator: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  #Provider
  path_provider: ^2.1.3


  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
