// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhJXjfekkHrjyOjY12CoCF7cyDzNFpdIg',
    appId: '1:916509059632:web:f03f08fb186591db79dbf5',
    messagingSenderId: '916509059632',
    projectId: 'demoauth-259e9',
    authDomain: 'demoauth-259e9.firebaseapp.com',
    databaseURL: 'https://demoauth-259e9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'demoauth-259e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHn0AHdm8RMYz5xZuaMU4wWwg8XsH2BrI',
    appId: '1:916509059632:android:c23f1134fd3e444b79dbf5',
    messagingSenderId: '916509059632',
    projectId: 'demoauth-259e9',
    databaseURL: 'https://demoauth-259e9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'demoauth-259e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAPmJdz1TNlQ6_V2ZTr59vBdxTl5ECbfo',
    appId: '1:916509059632:ios:88969b2c1a7fad3879dbf5',
    messagingSenderId: '916509059632',
    projectId: 'demoauth-259e9',
    databaseURL: 'https://demoauth-259e9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'demoauth-259e9.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAPmJdz1TNlQ6_V2ZTr59vBdxTl5ECbfo',
    appId: '1:916509059632:ios:88969b2c1a7fad3879dbf5',
    messagingSenderId: '916509059632',
    projectId: 'demoauth-259e9',
    databaseURL: 'https://demoauth-259e9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'demoauth-259e9.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhJXjfekkHrjyOjY12CoCF7cyDzNFpdIg',
    appId: '1:916509059632:web:e1e0e052cccb281779dbf5',
    messagingSenderId: '916509059632',
    projectId: 'demoauth-259e9',
    authDomain: 'demoauth-259e9.firebaseapp.com',
    databaseURL: 'https://demoauth-259e9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'demoauth-259e9.appspot.com',
  );
}
